### ISSUE TITLE
Setup Docker101 for WWCode ATX

### ISSUE THREAD

**Issue by joheec** [asb-spark/docker101#6]
## Problem Statement
- To utilize GitHub Codespaces for event, will need a repo that meets requirements

## Tasks
- [x] Create docker101 repo in codespaces-lab
- [x] Create team for codespaces-lab and assign to docker101
- [x] Add attendees to codespaces-lab/docker101
