### ISSUE TITLE
Update Documentation on CSE Session Setup

### ISSUE THREAD

**Issue by joheec** [asb-spark/docker101#7]
## Problem Statement
- Want to disperse knowledge on how to successfully promote a event and setup the logistics

## Proposed Solution
- Document in Teams > RDC > General > Wiki > CSE Session Setup

## Tasks
- [ ] Formalize `Promotion` steps
- [ ] Formalize `GiHub Form Creation` steps
- [x] Formalize `Bart-o-mation` steps
